# Generated by Django 5.1.2 on 2024-11-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_zapatilla_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
