# Generated by Django 5.1.2 on 2024-11-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_zapatilla_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatillas'),
        ),
    ]
