# Generated by Django 5.1.2 on 2024-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_extraperfil_fecha_extraperfil_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraperfil',
            name='profesion',
            field=models.CharField(max_length=20),
        ),
    ]
